-- CREATE TABLE USER
CREATE TABLE IF NOT EXISTS users (
       id INT PRIMARY KEY AUTO_INCREMENT,
       email VARCHAR(255) UNIQUE NOT NULL,
       name VARCHAR(255),
       country VARCHAR(2) ENUM('US', 'CO', 'TN') DEFAULT 'US' NOT NULL,
)
